# 配置文件
server:
    port: 3000

database:
    driver: mysql
    user: root
    passwd: root
    addr: 127.0.0.1
    port: 3306
    dbName: xiongmao
    zone: Asia/Shanghai

jwt:
    key: xiongmao

mqtt:
    server: tcp://127.0.0.1:1883
    clientID: xiongmao
    username: admin
    password: public
    topic: xiongmao/+

log:
    path: logger
    xiongmao: true
    sql: true