# 配置文件
server:
    port: 3000

database:
    driver: mysql
    user: root
    passwd: root
    addr: 127.0.0.1
    port: 3306
    dbName: xiongmao
    zone: Asia/Shanghai

casbin:
    secretKey: xiongmao

log:
    path: logger
    panda: true
    sql: true